---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 746058077879705600-tXNJul1yUUSl6Zq9z9NPYKW1Pk33wtf
:access_token_secret: btSTU7h3GfBiMFrL5p0JoGskto7p5cdLGAZHL6XhNoHss
